import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { normalize } from '../src/normalize.js';

// A REAL HoYoLAB account extraction (os_usa, 63 characters), scrubbed via
// @buer/core's `scrubRaw` (see the report this task produced for exactly how
// — packages/core/test/fixtures/real-account.scrubbed.json was generated by
// running the raw extraction through `scrubRaw` and saving the result
// unmodified). This is the "Spike 1 follow-through" regression test: before
// the FightProp property map / flat-substat / times+1 fixes, normalize()
// threw `property_type desconhecido: 6` on this exact payload.
const fixtureText = readFileSync(
  new URL('./fixtures/real-account.scrubbed.json', import.meta.url),
  'utf8',
);
const scrubbed = JSON.parse(fixtureText) as { list: unknown; detail: unknown; account: unknown };

describe('normalize() em conta real (escovada)', () => {
  it('nunca contém o UID/nickname reais (o repo é público)', () => {
    // Cinturão de segurança além do grep manual documentado no report: se
    // alguém um dia re-gerar este fixture sem passar por scrubRaw, o teste
    // falha em vez de vazar silenciosamente em CI.
    expect(fixtureText).not.toContain('607871249');
    expect(fixtureText).not.toContain('Lincoide');
  });

  it('normaliza as 63 personagens sem lançar', () => {
    const result = normalize({ list: scrubbed.list, detail: scrubbed.detail });
    expect(result.characters).toHaveLength(63);
    for (const c of result.characters) {
      expect(c.charKey).toBeTruthy();
      expect(c.contentHash).toMatch(/^[0-9a-f]{64}$/);
      expect(c.doc.artifacts.length).toBeGreaterThanOrEqual(0);
    }
  });

  it('accountHash é estável entre duas execuções', () => {
    const r1 = normalize({ list: scrubbed.list, detail: scrubbed.detail });
    const r2 = normalize({ list: scrubbed.list, detail: scrubbed.detail });
    expect(r2.accountHash).toBe(r1.accountHash);
    expect(r2.characters.map((c) => c.contentHash)).toEqual(r1.characters.map((c) => c.contentHash));
  });

  it('reconstrói substats 5★ para tiers plausíveis (1-4), sem degradar as peças reais', () => {
    const result = normalize({ list: scrubbed.list, detail: scrubbed.detail });
    // Sandrone (10000133) — primeira personagem do extract, peças 5★ com
    // substats plano (HP/DEF/EM) e percentual (crit/ER) misturados.
    const sandrone = result.characters.find((c) => c.charKey === '10000133');
    expect(sandrone).toBeDefined();
    const flower = sandrone!.doc.artifacts.find((a) => a.slot === 1)!;
    expect(flower).toBeDefined();
    for (const [, , tier] of flower.subs) expect(tier).toBeGreaterThanOrEqual(1);
    // O substat plano de ATQ% (property_type 6) e EM (28, flat) da flor
    // devem ter sido reconstruídos com valor exibido intacto (sem
    // "209.0"-style corruption) — spot-check pelos property_type reais.
    const flatEM = flower.subs.find((s) => s[0] === 28);
    expect(flatEM).toBeDefined();
    expect(Number.isInteger(flatEM![1])).toBe(true); // EM é plano: sem decimal.
  });

  it('todo substat 5★ é reconstruído com exatidão (nunca degrada para o fallback tier=1 por engano)', () => {
    // Confirma que a maioria esmagadora das ~494 substats 5★ da conta real
    // bate exatamente com as tabelas de tier (ver report) — usa a proporção
    // de tier=1 entre os planos como proxy: se o fallback estivesse sendo
    // usado sistematicamente, essa proporção seria bem mais alta que a
    // esperada por acaso (tier 1 é só 1 dos 4 tiers possíveis).
    const result = normalize({ list: scrubbed.list, detail: scrubbed.detail });
    let fiveStarSubs = 0;
    let tier1Count = 0;
    for (const c of result.characters) {
      for (const a of c.doc.artifacts) {
        if (a.rarity !== 5) continue;
        for (const [, , tier] of a.subs) {
          fiveStarSubs++;
          if (tier === 1) tier1Count++;
        }
      }
    }
    expect(fiveStarSubs).toBeGreaterThan(400);
    // Tier 1 sozinho não deveria dominar (isso indicaria fallback
    // sistemático em vez de reconstrução real).
    expect(tier1Count / fiveStarSubs).toBeLessThan(0.6);
  });
});
